
[app]
    root_background  = {}
    input_text = { background = "#fff", foreground = "black", font = "Calibri 12" }

[search]
    search_bar = { bg = "#eee", fg = "black", bd = 0, relief = "flat", font = ["Segoe UI", "11"] }
    result = { font = "Calibri 12" }
    result_selected = { bg = "#0af", fg = "white" }
    result_deselected   = { bg = "#eee", fg = "black" }
    background = { background = "#fff" }

[toolbar]
    button = { relief = "solid", bd = 0, highlightthickness = 0, font = ["Segoe UI", "10"] }
    button_selected   = { background = "#0af", foreground = "white" }
    button_deselected = { background = "#ccc", foreground = "black" }

    action_button = { background = "#fa0" }

    spacer     = { background = "#ddd" }
    background = { background = "#ddd" }

[tools]
    swap_cursor = { outline="white", width=3, dash=[5, 2] }

[beet_view]
    canvas = {}
    center_circle = { fill = "grey90", width = 0 }
    cursor = { outline = "black" }

    [beet_view.cell]
        background = { fill = "#7a6", width = 2}
        movable_pattern = { width = 2, dash = [10, 5] }
        plant_text = { font = ["Segoe UI", "12"] }
        joker_text = { font = ["Monospace", "20"] }

    [beet_view.cell.quality]
        gradient = [ "#e64369", "#f5c651", "#76d44e", "#40c791" ]
        # How many additional colors to add between two items of the gradient
        gradient_smoothing = 3
