
[app]
    root_background  = {}
    input_text = { background = "#fff", foreground = "black", font = "Calibri 12" }

[toolbar]
    button = { relief = "solid", bd = 0, highlightthickness = 0 }
    button_selected   = { background = "#0af", foreground = "white" }
    button_deselected = { background = "#ccc", foreground = "black" }

    action_button = { background = "#fa0" }

    spacer     = { background = "#ddd" }
    background = { background = "#ddd" }

[tools]
    swap_cursor = { outline="white", width=3, dash=[5, 2] }

[beet_view]
    canvas = {}
    center_circle = { fill = "grey90", width = 0 }
    cursor = { outline = "black" }

    [beet_view.cell]
        background = { fill = "#7a6", width = 2}
        movable_pattern = { width = 2, dash = [10, 5] }
        plant_text = { font = "Calibri 12" }
        joker_text = { font = "Monospace 20"}
